apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-backup.fullname" . }}
data:
  GRAFANA_URL: "{{ .Values.env.grafanaUrl }}"
  GRAFANA_TOKEN: "{{ .Values.env.grafanaToken }}"
  AWS_ENDPOINT_URL: "{{ .Values.env.S3URL }}"
  AWS_S3_BUCKET_NAME: "{{ .Values.env.S3BucketName }}"
  AWS_S3_BUCKET_KEY: "{{ .Values.env.S3BucketKey }}"
  AWS_DEFAULT_REGION: "{{ .Values.env.S3Region }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.env.S3AccessKey }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.env.S3SecretAccessKey }}"
  {{- if .Values.restore.enabled }}
  RESTORE: "true"
  ARCHIVE_FILE: "{{ .Values.restore.archiveFile }}"
  {{- end }}
