{{- if .Values.restore.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "grafana-backup.fullname" . }}
  labels:
    app: {{ include "grafana-backup.fullname" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ include "grafana-backup.fullname" . }}
    spec:
      restartPolicy: "Never"
      containers:
        - name: {{ include "grafana-backup.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "grafana-backup.fullname" . }}
---
{{- end }}